# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-07 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='id',
            field=models.UUIDField(default=b'564b6612-6d5d-45ac-a6b6-66c50aa6a66e', editable=False, primary_key=True, serialize=False),
        ),
    ]
